spring:
  redis:
    database: 0
    host: ojRedis.com
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        time-between-eviction-runs: 30000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/queoj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: queue-lzr54545
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml
  type-enums-package: xyz.lizhaorong.queoj.enums
logging:
  level:
    xyz:
      lizhaorong: debug

server:
  port: 8888


#  host: smtp.qq.com
#  username: 853681401@qq.com
#  password: emkdlgsznwavbfca
#  senderName: 鹊
smtp:
  host: smtp.126.com
  password: WDCFQFYXWFMCJRPH
  sender-name:  鹊
  username: breadNetwork@126.com