spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        time-between-eviction-runs: 30000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://ssacgn.online:3306/queoj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: o@S$9i3r6V
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_empty
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml
  type-enums-package: top.quezr.hqoj.enums
logging:
  level:
    top:
      quezr: debug

server:
  servlet:
    context-path: /hqoj
  port: 8989


#  host: smtp.qq.com
#  username: 853681401@qq.com
#  password: emkdlgsznwavbfca
#  senderName: 鹊
smtp:
  host: smtp.126.com
  password: WDCFQFYXWFMCJRPH
  sender-name:  鹊
  username: breadNetwork@126.com


elasticsearch:
  host: ojEs.com
  port: 9200

