spring:
  application:
    name: backend
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        time-between-eviction-runs: 30000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://ssacgn.online:3306/queoj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: o@S$9i3r6V
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_empty
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml
  type-enums-package: top.quezr.hqoj.enums
logging:
  level:
    top:
      quezr: debug

server:
  servlet:
    context-path: /hqoj
  port: 8989

smtp:
  host: smtp.126.com
  password: WDCFQFYXWFMCJRPH
  sender-name:  鹊
  username: breadNetwork@126.com

eureka:
  client:
    # 本身是客户端，需要注册
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://ojEureka.com:7001/eureka/
  instance:
    instance-id: backend
    # 访问路径可以显示ip地址
    prefer-ip-address: true
    # eureka客户端向服务端发送心跳的时间间隔，默认30喵
    lease-renewal-interval-in-seconds: 30
    # eureka服务端在收到最后一次心跳后的等待时间上限，默认为90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 90